apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-netpol-allowdns
  annotations:
    policies.kyverno.io/description: allow dns traffic
spec:
  background: false
  rules:
    - name: default-deny
      match:
        resources:
          kinds:
            - Namespace
          selector:
            matchLabels:
              allow-dns-traffic: "true"
      generate:
        kind: CiliumNetworkPolicy
        apiVersion: cilium.io/v2
        name: allow-dns
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          spec:
            endpointSelector:
              matchLabels: {}
            egress:
            - toEndpoints:
              - matchLabels:
                  "k8s:io.kubernetes.pod.namespace": kube-system
                  "k8s:k8s-app": kube-dns


